docs/_data/toc.yml

This fixes a bug where translated languages (korean, japanese) would not handle external links back to the developer site correctly, but would instead process those links to have them point to the language specific pages. This is an edge case and will only be an issue while we have the dev site point with external links to the developer site (e.g. links going from developer.shotgunsoftware.com to for example developer.shotgunsoftware.com/tk-multi-publish2). The solution is described [here](https://github.com/untra/polyglot#disabling-url-relativizing) and is simple, but manual - just prepend the url with a space.

i18n External Link Fixes

---

docs/en/toolkit/toolkit_basics_guides/advanced_config.md
docs/en/toolkit/toolkit_basics_guides/installing_app.md

- Guide 1: changed the capitalization of the TOC string, but also changed its content from "Advanced Setup" to "Configuration setup" to better match the title of the doc, "Getting started with configurations"
- Guide 3: Changed TOC from "Installing an app" to "Adding and app" and fixed capitalization

Case and content consistency across Guides' TOC titles and doc titles

---

docs/en/toolkit/learning-resources/tutorial.md

Remove "Overview" heading and add "Pipeline Tutorial" heading.

[minor] Fix title on Pipeline Tutorial page.

---

docs/en/toolkit/learning-resources/guides/installing_app.md

Quite a few users will use this guide to figure out how to add apps that have never been added before, as such we should inform them of the `tank cache_apps` required step if they are using a centralized configuration.
I've also modified the way the Linux/Mac vs Windows tank commands are listed. As I was adding a section on using the tank command for caching apps I thought it would make sense to change the push command so that the windows version is not a note as well. The reason I did this is that it felt like Windows as a side note, and we have a lot of Windows users.

Adding tank cache_app instructions

---

docs/_data/landing_page.yml

When we switched over to using UID URLs, most internal links could remain relative.  However, because Jekyll generates the landing pages (from the landing_page.yml template) differently, we can't use relative paths here.

Update landing_page.yml to use UID permalinks

---

docs/_data/en/toc_text.yml
docs/_data/toc.yml
docs/en/rv/forums.md

Our RV forums are pretty defunct; let's direct people to the RV forum instead. In doing so, got rid of the two links to RV forums (Troubleshooting and Extending) in favor of a single one.

RV forums now point to Discourse

---

docs/ja/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md
docs/zh_CN/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md

Fixes incorrectly quoted titles in translated page names for `fix-ssl-certificate-verify-failed.md`.

Fix incorrectly quoted page titles in translated pages

---

docs/ja/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md
docs/zh_CN/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md

unicode double quotes in page headers + colon character was breaking yaml and thus the page was not being built. replaced the unicode double quotes with ascii double quotes. slack thread with details (and jokes) here: https://autodesk.slack.com/archives/C14NNUA85/p1573146701077300

replaced unicode quotes in header with ascii quotes

---

docs/en/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md

As per the subject. This should cause builds to fail on site-breaking errors that used to end up as warnings from Jekyll.

SG-13614: bundles a new tk-doc-generator that fails properly on jekyll build error

---

docs/en/guides/python-3-best-practices.md

Fixes a broken link in the Python 3 Porting Best Practices document.

Fix broken link in Python 3 Porting Best Practices doc

---

docs/_data/en/toc_text.yml

jira bridge isn't beta anymore!

removed "beta" from jira bridge links

---

docs/_includes/product

The include will be resolved at build time, and is set to "Shotgun"

SG-20956: Allows for an include to be used for a product name

---

docs/en/trusted-solutions/tier1/setup/tuning.md

**Summary**
- Add CloudOS VPC ID to the S3 bucket policy for isolation to account for the scenario where a client's bucket is also in the us-east-1 region.

Add cloudOS VPC to bucket policy tuning

---

.travis.yml

Add appropriate build/deploy for developer.shotgridsoftware.com to Travis CI.
We need to build the site twice since the URL is used during the build process to generate absolute URLs.  Then, while we're continuing to maintain two developer sites, we will need to deploy to both.

Add build/deploy for developer.shotgridsoftware.com

---

.travis.yml
docs/CNAME

Previously the CNAME file for Github Pages deploy had been kept as a file in the content repo and pushed through the build into the target repo.  Now that we're targeting multiple site URLs, this approach does not work, so we'll use the `fqdn` option for pages deploy provider to generate a CNAME file for each target appropriately.

Specify CNAME when deploying to gh-pages

---

.github/workflows/publish-docs.yml
README.md

Fixes an issue caused by publishing to the same branch name as the source (master) by changing the publish destination on the GH pages repo to `gh-pages`.  Also updates the CI badge in the `README.md`

Small fixes for publish CI

---

docs/en/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md
docs/ja/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md
docs/ko/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md
docs/zh_CN/quick-answers/troubleshooting/fix-ssl-certificate-verify-failed.md

Replace references to {% include product %}_API_CACERTS with hardcoded string SHOTGUN_API_CACERTS.

Replace ShotGrid_API_CACERTS with SHOTGUN_API_CACERTS

---

docs/en/guides/pipeline-integrations/development/sgtk-developer-bootstrapping.md

The bootstrapping doc is incorrect and doesn't pass the script/human user to the `ToolkitManager` during bootstrap.
This was brought up by Issue #127

SG-21566: Use custom user when bootstrapping.

---

.github/workflows/generate-preview.yml

This PR adds a new step **Bundle config** in the Github Action **Generate-Preview** to remove deprecated flag **--deployment** when building the docs.
The usage of this deprecated flag was causing that commands like **jekyll** were not found.
The deprecation message was:
```
[DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local deployment 'true'`, and stop using this flag
```
The jekyll command not found was:
```
bundler: command not found: jekyll
```

Add config step for bundle and fix issues like jekyll command was not found

---

.github/workflows/publish-docs.yml

This PR adds a new step **Bundle config** in the Github Action **Publish-Docs** to remove deprecated flag **--deployment** when building the docs.
The usage of this deprecated flag was causing that commands like **jekyll** were not found.
The deprecation message was:
```
[DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local deployment 'true'`, and stop using this flag
```
The jekyll command not found was:
```
bundler: command not found: jekyll
```

Add config step for bundle in publish docs workflow

---

docs/en/reference/pipeline-integrations/toolkit-engines/tk-create.md

`SHOTGUN_CREATE_DISABLE_TOOLKIT_INTEGRATION` is an env var that disables SGTK integration and prevents the error message from appearing. Admins should know about it

how to fix error message reported by users
