jekyll_config.yml

Added Analytics

---

README.md
docs/en/contribution.md

tweaks and followups to readme after visual tweaks.

Improved README

---

docs/_data/en/toc_text.yml
docs/_data/toc.yml

To be merged once the jira bridge docs come online.

Adds TOC link to Jira Bridge

---

.travis.yml

Non-content change: This upgrades the AWS S3 bucket we are using to generate previews.

Upgraded to new S3 bucket

---

docs/en/quick-answers/developing/maya-shelf-app-launcher.md
docs/en/quick-answers/developing/toolkit-core-event-daemon.md
docs/en/quick-answers/developing/update-config-with-api.md
docs/en/quick-answers/troubleshooting/3dsmax-crashes-on-startup.md
docs/en/quick-answers/troubleshooting/nuke-path-environment-variable.md
docs/en/quick-answers/troubleshooting/performance-troubleshooting.md
docs/en/toolkit/env_config_ref.md
docs/en/toolkit/learning-resources/guides/dynamic_filesystem_configuration.md
docs/en/toolkit/learning-resources/guides/editing_app_setting.md
docs/en/toolkit/learning-resources/guides/installing_app.md

Updating a bunch of Python and YAML code blocks to use syntax highlighting.

Updating code example to use syntax highlighting

---

docs/en/toolkit/learning-resources/guides/dynamic_filesystem_configuration.md
docs/en/toolkit/learning-resources/guides/editing_app_setting.md
docs/en/toolkit/learning-resources/guides/installing_app.md

Hang found a bunch of dead links and other issues in the process of localizing some docs in the dev docs site. This pull request addresses all of his notes in the following JIra tickets:
https://dts.autodesk.com/browse/SHOT20-99
https://dts.autodesk.com/browse/SHOT20-105
https://dts.autodesk.com/browse/SHOT20-106
https://dts.autodesk.com/browse/SHOT20-107

fixed dead links, other cleanup

---

jekyll_config.yml

Adds swift type search metadata to all pages.

Adds swift-type metadata to wrap around content

---

docs/en/toolkit/frameworks.md

Reworded some of the sentences, and added a link to the core API section on frameworks.

Add link to core API framework documentation

---

docs/en/offerings/spc/knowledge/connecting.md
docs/en/offerings/spc/knowledge/direct_connect.md
docs/en/offerings/spc/knowledge/direct_connect_onboarding.md
docs/en/offerings/spc/knowledge/private_link.md
docs/en/offerings/spc/knowledge/s3.md
docs/en/offerings/spc/knowledge/vpc_iam_sec.md

Update AWS knowledge section [WIP]

---

docs/en/guides/pipeline-integrations/development/sgtk-developer-bootstrapping.md

Added some clarification around how to import sgtk.

Added more details on how to import sgtk.

---

docs/en/reference/pipeline-integrations/env-config-ref.md

fixed a few broken links in the Environment Config Ref doc

fixed dead links

---

docs/en/offerings/spc/setup/s3_bucket.md

Also fixed permission issues with other CloudFormation links.

S3 bucket doc now use a CloudFormation link on S3

---

docs/en/trusted-solutions/tier1.md
docs/en/trusted-solutions/tier1/setup/s3_replication.md
docs/en/trusted-solutions/tier1/setup/setup.md

Media Isolation

---

docs/en/guides/pipeline-integrations/getting-started/editing_app_setting.md

per https://autodesk.slack.com/archives/C0M5YE2DV/p1600181253142500

fixed a broken link to Env Config Ref

---

docs/en/event-daemon/event-daemon-api.md
docs/en/event-daemon/event-daemon-configuration.md
docs/en/event-daemon/event-daemon-example-plugins.md
docs/en/event-daemon/event-daemon-installation.md
docs/en/event-daemon/event-daemon-plugins.md
docs/en/event-daemon/event-daemon-technical-details.md
docs/en/event-daemon/event-daemon.md

Add 7 files from shotgunEvents tool over to markdown in the developer site

SG-21012 Add event MD files and replace shotgun instances

---

.travis.yml

Fix a typo that caused a conditional job to never execute.

Fix build/deploy for developer.shotgridsoftware.com

---

.travis.yml

* deploy developer.shotgridsoftware.com to shotgunsoftware.github.io repo
* remove secondary deploy for shotgridsoftware.github.io

Update CI to use new custom domain

---

docs/_data/en/toc_text.yml
docs/_data/toc.yml

Addressing: SG-23241, SG-23242, SG-23243, SG-23244, SG-23245, SG-23246

updates to links in tree

---

docs/en/reference/pipeline-integrations/toolkit-configuration/toolkit-config-ref.md
docs/ja/reference/pipeline-integrations/toolkit-configuration/toolkit-config-ref.md
docs/ko/reference/pipeline-integrations/toolkit-configuration/toolkit-config-ref.md
docs/zh_CN/reference/pipeline-integrations/toolkit-configuration/toolkit-config-ref.md

Thanks to @tannazie, a fix for some broken image URLs

Update toolkit-config-ref.md (#231)

---

docs/ja/reference/pipeline-integrations/env-config-ref.md
docs/ja/reference/pipeline-integrations/toolkit-apps/tk-multi-pythonconsole.md
docs/ko/quick-answers/administering/sg-desktop-run-on-ubuntu.md
docs/ko/reference/pipeline-integrations/env-config-ref.md
docs/ko/reference/pipeline-integrations/toolkit-apps/tk-multi-pythonconsole.md
docs/zh_CN/quick-answers/administering/sg-desktop-run-on-ubuntu.md
docs/zh_CN/reference/pipeline-integrations/env-config-ref.md
docs/zh_CN/reference/pipeline-integrations/toolkit-apps/tk-multi-pythonconsole.md

This PR replaces ZD urls to AKN and developer urls

SG-21170 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

docs/en/guides/pipeline-integrations/administration/advanced-toolkit-administration.md
docs/en/guides/pipeline-integrations/administration/config-staging-and-rollout.md
docs/en/guides/pipeline-integrations/getting-started/installing_app.md
docs/en/guides/pipeline-integrations/workflows/pipeline-tutorial.md
docs/en/reference/pipeline-integrations/toolkit-apps/tk-multi-pythonconsole.md
docs/ja/guides/pipeline-integrations/administration/advanced-toolkit-administration.md
docs/ja/guides/pipeline-integrations/administration/config-staging-and-rollout.md
docs/ja/guides/pipeline-integrations/getting-started/installing_app.md
docs/ja/guides/pipeline-integrations/workflows/pipeline-tutorial.md
docs/ja/quick-answers/administering/sg-desktop-run-on-ubuntu.md
docs/ko/guides/pipeline-integrations/administration/advanced-toolkit-administration.md
docs/ko/guides/pipeline-integrations/administration/config-staging-and-rollout.md
docs/ko/guides/pipeline-integrations/getting-started/installing_app.md
docs/ko/guides/pipeline-integrations/workflows/pipeline-tutorial.md
docs/zh_CN/guides/pipeline-integrations/administration/advanced-toolkit-administration.md
docs/zh_CN/guides/pipeline-integrations/administration/config-staging-and-rollout.md
docs/zh_CN/guides/pipeline-integrations/getting-started/installing_app.md
docs/zh_CN/guides/pipeline-integrations/workflows/pipeline-tutorial.md

This PR replaces ZD urls to AKN and developer urls

SG-21170-ROUND2 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

docs/en/quick-answers/administering/share-assets-between-projects.md

Migrated changes from a fork to a branch for CI.

[SG-25403] Added updated technique for cross-project linking - branch

---

docs/en/trusted-solutions/tier1/features/media_traffic_isolation.md
docs/en/trusted-solutions/tier1/setup/media_segregation.md
docs/en/trusted-solutions/tier1/setup/s3_bucket.md
docs/en/trusted-solutions/tier1/setup/s3_replication.md

* Update Isolation features setup to use the new self-serve workflow

Isolation Feature Set setup update

---

docs/en/guides/pipeline-integrations/administration/file-system-config-reference.md

This pr removes the documentation about creating a custom Pipeline step using a custom entity.

SG-25669 Client wants to Modify Schema to Include a Custom Entity for Grouping Tasks Below a Step

---

jekyll_config.yml

This PR updates the tk-doc-generator latest commit in master which implements the Tealium Script as part of the Tealium instrumentation tagging plan for the developer.shotgridsoftware.com site.

SG-27879 Make Developer Shotgrid Site Compliant With Our Privacy

---

docs/en/event-daemon/event-daemon-installation.md

I looked at https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links to validate the syntax and choose to use <> instead of [] since I was not sure if removing the () would have worked...

SG-30095 Fix empty link

---

docs/en/action-menu-items/custom-browser-protocols.md

- Updated the section saying we should remove the lines from the plist so this only applies to Big Sur and not Monterey. 
- Removed the first line for removing from the plist files for Big Sur.
- Added a debugging tip AppleScript snippet under MacOS for try on error.

SG-30086 AMI Custom Protocol Doc Updates

---

docs/en/action-menu-items/custom-browser-protocols.md

- Updating the Python script for python 2 and 3 cross-compatibility.

SG-30086 More AMI Custom Protocol Updates

---

docs/en/action-menu-items/action-menu-items-create.md
docs/en/guides/pipeline-integrations/administration/file-system-config-reference.md
docs/en/guides/pipeline-integrations/development/sgtk-developer-app.md

Fixes flagged from localization

---

docs/en/guides/webhooks.md

Updates to address documentation concerns.
1. Provide more information about Supported Events
2. Add explanations around Event Creation/Update events. In particular, why do new entities with field values for which an update webhook exists not fire an update delivery.
3. Geographic event source, Throttling

for SG-31031 adding documentation for custom events, throttling

---

docs/en/guides/webhooks.md

@shaynacohen  I missed your change in the previous PR.

for SG-31031 adding missed text edit

---

docs/en/trusted-solutions/tier1/setup/tuning.md

Add new ShotGrid & Transcoder VPC and NAT Gateways to Isolation documentation
vpc-09441e47c87a28dd4 SHOTTS1-prd
- 54.145.164.228   
- 3.224.231.216
- 100.26.115.40
vpc-098e0ff163debc966 SHOTGUN-prd
- 34.195.16.11
- 3.234.125.244
- 3.234.133.244

Update isolation VPCs and NAT Gateways
